Browser=Chrome
Browser.Version=Latest
Environment=QA
Java.Version=17
OS=Windows
Framework=Selenium + TestNG + Cucumber
Execution.Mode=Local
Allure.Version=2.29.0
Cucumber.Version=7.34.8
Selenium.Version=4.49.0
TestNG.Version=7.12.0