# Project 1 - App.vwo.com
url=https://app.vwo.com
qa_url=https://stage.vwo.com
current_url=https://app.vwo.com/#/login
current_title="Login - VWO"

username=contact+aug@thetestingacademy.com
password=TtxkgQ!s$rJBk85

invalid_username=admin@admin.com
invalid_password=Test@2024

expected_username=Aman
error_message=Your email, password, IP address or location did not match
invalid_error_message=Pramod email, password, IP address or location did not match
browser=chrome

# Project 2 - Orange HR
ohr_username=admin
ohr_password=Hacker@4321
ohr_expected_username=PIM
ohr_url = https://awesomeqa.com/hr/web/index.php/auth/login

# Project 3 - Katalon App
katalon_url=https://katalon-demo-cura.herokuapp.com/

# Cloud Grid Configuration
execution.mode=local
browserstack.username=YOUR_BROWSERSTACK_USERNAME
browserstack.accesskey=YOUR_BROWSERSTACK_ACCESS_KEY
lambdatest.username=YOUR_LAMBDATEST_USERNAME
lambdatest.accesskey=YOUR_LAMBDATEST_ACCESS_KEY
selenium.grid.url=http://localhost:4444/wd/hub

# Wait Configuration
default.timeout=20
default.polling=500

# Database Configuration (Optional)
db.url=jdbc:mysql://localhost:3306/testdb
db.username=root
db.password=password