# VWO App - Production Environment
url=https://app.vwo.com

username=${VWO_USERNAME}
password=${VWO_PASSWORD}

invalid_username=${VWO_INVALID_USERNAME}
invalid_password=${VWO_INVALID_PASSWORD}

expected_username=${VWO_EXPECTED_USERNAME}
error_message=Your email, password, IP address or location did not match

current_url=https://app.vwo.com/#/login
current_title=Login - VWO

browser=chrome
execution.mode=cloud
default.timeout=20
default.polling=500
