# VWO App - QA Environment
url=https://app.vwo.com

username=contact+aug@thetestingacademy.com
password=TtxkgQ!s$rJBk85

invalid_username=admin@admin.com
invalid_password=Test@2024

expected_username=Aman
error_message=Your email, password, IP address or location did not match

current_url=https://app.vwo.com/#/login
current_title=Login - VWO

browser=chrome
execution.mode=local
default.timeout=30
default.polling=500
