# Katalon Demo App - Production Environment
url=https://katalon-demo-cura.herokuapp.com/

username=${KATALON_USERNAME}
password=${KATALON_PASSWORD}
invalid_username=${KATALON_INVALID_USERNAME}
invalid_password=${KATALON_INVALID_PASSWORD}
expected_header=Make Appointment
error_message=Login failed! Please ensure the username and password are valid.

browser=chrome
execution.mode=local
default.timeout=30
default.polling=500
