# OrangeHRM App - QA Environment
url=https://awesomeqa.com/hr/web/index.php/auth/login

username=admin
password=Hacker@4321

expected_username=PIM
error_message=Invalid credentials

browser=chrome
execution.mode=local
default.timeout=30
default.polling=500
