# OrangeHRM App - QA Environment
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

username=Admin
password=admin123

expected_username=Dashboard
error_message=Invalid credentials

browser=chrome
execution.mode=local
default.timeout=30
default.polling=500
